### ISSUE TITLE
Please add jaxb-xjc dependency

### ISSUE THREAD

**Issue by robertlazarski** [veithen/xjc-maven-plugin#69]
With the latest source in git, I had to add this to the pom.xml in order to pass the Axis2 jaxws-integration tests: 

<dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-xjc</artifactId>
            <version>4.0.2</version>
</dependency>

**Comment by veithen** [comment]
`jaxb-xjc` is already a dependency of the plugin. Where do you want me to add the dependency to?

**Comment by robertlazarski** [comment]
My apologies as I listed an existing dependency and not the required dependency. 

In the latest Axis2 source code, commenting in the jaxws-integration code fails the unit tests with: 

Caused by: java.lang.ClassNotFoundException: org.glassfish.jaxb.runtime.v2.ContextFactory

By simply adding jaxb-runtime in addition to the existing jaxb-xjc fixes the issue for me.
